/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import clas.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author hneen.
 */
public class movie extends javax.swing.JFrame {

    /**
     * Creates new form movie
     */
    int id_customer;
    List<movieName> movielist;

    public movie() {
        initComponents();
    }
    public movie(int id_customer) {
        initComponents();
        this.id_customer=id_customer;
        getAllMovie();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adu_m4 = new javax.swing.JButton();
        adu_m1 = new javax.swing.JButton();
        adu_m2 = new javax.swing.JButton();
        adu_m3 = new javax.swing.JButton();
        adu_m7 = new javax.swing.JButton();
        adu_m6 = new javax.swing.JButton();
        kid_m2 = new javax.swing.JButton();
        adu_m5 = new javax.swing.JButton();
        kid_m1 = new javax.swing.JButton();
        kid_m4 = new javax.swing.JButton();
        kid_m3 = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));


        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Kid's movie");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Adult's movie");

        adu_m4.setBackground(new java.awt.Color(51, 51, 51));
        adu_m4.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi4.jpg")); // NOI18N
        adu_m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m4ActionPerformed(evt);
            }
        });

        adu_m1.setBackground(new java.awt.Color(51, 51, 51));
        adu_m1.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi1.png")); // NOI18N
        adu_m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m1ActionPerformed(evt);
            }
        });

        adu_m2.setBackground(new java.awt.Color(51, 51, 51));
        adu_m2.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi2.jpg")); // NOI18N
        adu_m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m2ActionPerformed(evt);
            }
        });

        adu_m3.setBackground(new java.awt.Color(51, 51, 51));
        adu_m3.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi3.jpg")); // NOI18N
        adu_m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m3ActionPerformed(evt);
            }
        });

        adu_m7.setBackground(new java.awt.Color(51, 51, 51));
        adu_m7.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi7.jpg")); // NOI18N
        adu_m7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m7ActionPerformed(evt);
            }
        });

        adu_m6.setBackground(new java.awt.Color(51, 51, 51));
        adu_m6.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi6.jpg")); // NOI18N
        adu_m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m6ActionPerformed(evt);
            }
        });

        kid_m2.setBackground(new java.awt.Color(51, 51, 51));
        kid_m2.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/kidmovi2.jpg")); // NOI18N
        kid_m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kid_m2ActionPerformed(evt);
            }
        });

        adu_m5.setBackground(new java.awt.Color(51, 51, 51));
        adu_m5.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/adumovi5.jpg")); // NOI18N
        adu_m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adu_m5ActionPerformed(evt);
            }
        });

        kid_m1.setBackground(new java.awt.Color(51, 51, 51));
        kid_m1.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/kidmovi1.jpg")); // NOI18N
        kid_m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kid_m1ActionPerformed(evt);
            }
        });

        kid_m4.setBackground(new java.awt.Color(51, 51, 51));
        kid_m4.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/kidmovi4.jpg")); // NOI18N
        kid_m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kid_m4ActionPerformed(evt);
            }
        });

        kid_m3.setBackground(new java.awt.Color(51, 51, 51));
        kid_m3.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/kidmovi3.jpg")); // NOI18N
        kid_m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kid_m3ActionPerformed(evt);
            }
        });

        logout_button.setBackground(new java.awt.Color(255, 204, 0));
        logout_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        logout_button.setForeground(new java.awt.Color(51, 51, 51));
        logout_button.setText("Log Out");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(adu_m1)
                                                        .addComponent(adu_m5))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(adu_m2)
                                                        .addComponent(adu_m6))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(adu_m7)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(adu_m3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(adu_m4))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(kid_m1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(kid_m2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(kid_m3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(kid_m4))
                                                        .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(adu_m4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adu_m2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adu_m3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adu_m1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adu_m6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adu_m5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adu_m7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kid_m1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kid_m2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kid_m3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kid_m4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>



    private void adu_m1ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==1 && id_customer!=0){
                        dispose();
                        movie_info d= new movie_info(id_customer,movie);
                        d.setTitle("movie_info");
                        d.setVisible(true);
            }
        }
    }

    private void adu_m2ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==2){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void adu_m3ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==3){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void adu_m4ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==4){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void adu_m5ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==5){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void adu_m6ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==6){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void adu_m7ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==7){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void kid_m1ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==8){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void kid_m2ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==9){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void kid_m3ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==10){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }

    private void kid_m4ActionPerformed(java.awt.event.ActionEvent evt) {
        for (movieName movie: movielist){
            if(movie.getItem_id()==11){
                dispose();
                movie_info d= new movie_info(id_customer,movie);
                d.setTitle("movie_info");
                d.setVisible(true);
            }
        }
    }


    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        login d= new login();
        d.setTitle("Dash Bord");
        d.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie().setVisible(true);
            }
        });
    }

    void getAllMovie()  {
        ResultSet resultSet=null;
        PreparedStatement getMovie=null;
        DB n = new DB();
        Connection dbconn = n.connectDB();

       try {
             getMovie = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM movie;");
             resultSet = getMovie.executeQuery();
            movielist = new ArrayList<movieName>();
            while (resultSet.next()) {
                movielist.add(new movieName(resultSet.getInt("movie_id"), resultSet.getString("movie_name"), resultSet.getDouble("movie_price"), resultSet.getString("age"), resultSet.getString("doration"), resultSet.getString("Language")));
            }
        }catch (Exception e){
           e.printStackTrace();
       }finally {
           try {
               resultSet.close();
               getMovie.close();
               dbconn.close();
           } catch (SQLException e) {
               e.printStackTrace();
           }
    }}

    // Variables declaration - do not modify
    private javax.swing.JButton adu_m1;
    private javax.swing.JButton adu_m2;
    private javax.swing.JButton adu_m3;
    private javax.swing.JButton adu_m4;
    private javax.swing.JButton adu_m5;
    private javax.swing.JButton adu_m6;
    private javax.swing.JButton adu_m7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kid_m1;
    private javax.swing.JButton kid_m2;
    private javax.swing.JButton kid_m3;
    private javax.swing.JButton kid_m4;
    private javax.swing.JButton logout_button;
    // End of variables declaration                   
}
