/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clas.DB;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hneen.
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        user_buttonGroup1.add(coustomer_radio);
        user_buttonGroup1.add(employee_radio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        user_buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        hello_lable = new javax.swing.JLabel();
        cinema_icon = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        username_labal = new javax.swing.JLabel();
        password_labal1 = new javax.swing.JLabel();
        phon_field1 = new javax.swing.JTextField();
        phone_labal1 = new javax.swing.JLabel();
        fullname_field2 = new javax.swing.JTextField();
        username_labal2 = new javax.swing.JLabel();
        login_labal = new javax.swing.JLabel();
        coustomer_radio = new javax.swing.JRadioButton();
        employee_radio = new javax.swing.JRadioButton();
        Sign_jButton = new javax.swing.JButton();
        login_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        hello_lable.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 24)); // NOI18N
        hello_lable.setForeground(new java.awt.Color(255, 204, 102));
        hello_lable.setText("Hello to our Cinema App!!");

        cinema_icon.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/cinema.png")); // NOI18N

        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        username_labal.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        username_labal.setForeground(new java.awt.Color(204, 204, 204));
        username_labal.setText("User name:");

        password_labal1.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        password_labal1.setForeground(new java.awt.Color(204, 204, 204));
        password_labal1.setText("Password:");

        phon_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phon_field1ActionPerformed(evt);
            }
        });

        phone_labal1.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        phone_labal1.setForeground(new java.awt.Color(204, 204, 204));
        phone_labal1.setText("Phone number:");

        fullname_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullname_field2ActionPerformed(evt);
            }
        });

        username_labal2.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        username_labal2.setForeground(new java.awt.Color(204, 204, 204));
        username_labal2.setText("fullname:");

        login_labal.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 24)); // NOI18N
        login_labal.setForeground(new java.awt.Color(255, 204, 153));
        login_labal.setText("Sign Up");

        coustomer_radio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        coustomer_radio.setForeground(new java.awt.Color(204, 204, 255));
        coustomer_radio.setText("coustomer");
        coustomer_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coustomer_radioActionPerformed(evt);
            }
        });

        employee_radio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        employee_radio.setForeground(new java.awt.Color(204, 204, 255));
        employee_radio.setText("Employee");
        employee_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_radioActionPerformed(evt);
            }
        });

        Sign_jButton.setBackground(new java.awt.Color(255, 204, 0));
        Sign_jButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Sign_jButton.setText("Sign Up");
        Sign_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_jButtonActionPerformed(evt);
            }
        });

        login_jButton.setBackground(new java.awt.Color(255, 204, 0));
        login_jButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_jButton.setText("Log In ");
        login_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(hello_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(username_labal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(employee_radio)
                                        .addComponent(password_labal1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPasswordField1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(coustomer_radio)
                                            .addGap(23, 23, 23)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phone_labal1)
                                .addGap(22, 22, 22)
                                .addComponent(phon_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(username_labal2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullname_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(cinema_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(login_labal))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Sign_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(login_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(hello_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cinema_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_labal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username_labal2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fullname_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phon_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_labal1))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username_labal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password_labal1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coustomer_radio)
                    .addComponent(employee_radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Sign_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(510, Short.MAX_VALUE)
                    .addComponent(login_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void phon_field1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void fullname_field2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void employee_radioActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void coustomer_radioActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void login_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        login d= new login();
        d.setTitle("Dash Bord");
        d.setVisible(true);
    }

    private void Sign_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String name=fullname_field2.getText();
        String phone =phon_field1.getText();
        String username=username_field.getText();
        String password=jPasswordField1.getText();

        if(name.isEmpty() || password.isEmpty() || phone.isEmpty() ||  username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "should not be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            //start the login process
            if (coustomer_radio.isSelected() || employee_radio.isSelected()){
                if (PhoneCheck(phone)) {
                    usersingup(name, phone,username, password);
                }
            }else {
                JOptionPane.showMessageDialog(this, "Are Customer or Employee? Select one !","Error", JOptionPane.ERROR_MESSAGE);

            }
        }    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    public boolean PhoneCheck(String phone){
        boolean phoneCheck=false;
        if (phone.matches("[0-9]+")){
            if (phone.contains("05")) {
                if (phone.length() == 10) {
                    phoneCheck = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect Phone number  Please Re-Enter Phone number", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else  {
            JOptionPane.showMessageDialog(this, "Incorrect Phone number Please Re-Enter Phone number (Just numbers!!)","Error", JOptionPane.ERROR_MESSAGE);
        }
        return phoneCheck;
    }

    private void  usersingup (String name, String phone,String username, String password){
        DB t=new DB();
        Connection dbconn=t.connectDB();
        int last_id=0;
        PreparedStatement st1=null;
        PreparedStatement st=null;
        PreparedStatement insert_id=null;
        PreparedStatement id_p=null;
        ResultSet resultSet=null;
        try {
            id_p=(PreparedStatement) dbconn.prepareStatement("SELECT * FROM person");
            resultSet=id_p.executeQuery();

            while (resultSet.next()){
                last_id = resultSet.getInt("id");
            }

            if (coustomer_radio.isSelected()){
                int id=last_id+1;
                insert_id=(PreparedStatement) dbconn.prepareStatement("insert into person(id) value (?)");
                insert_id.setInt(1,id);
                int res =insert_id.executeUpdate();
                if (res==1){
                    st = (PreparedStatement) dbconn.prepareStatement("insert into customer(coustomer_id,coustomer_name ,coustomer_Phone) values (?,?,?)  ");
                    st.setInt(1, id);
                    st.setString(2, name);
                    st.setString(3, phone);
                    int res2 = st.executeUpdate();
                    if (res2 == 1) {
                        st1 = (PreparedStatement) dbconn.prepareStatement("insert into account(username ,password, person_id, rule) values (?,?,?,?)");
                        st1.setString(1, username);
                        st1.setString(2, password);
                        st1.setInt(3, id);
                        st1.setString(4, "c");
                        int res1 = st1.executeUpdate();
                        if (res1==1)
                            JOptionPane.showMessageDialog(this, "customer Added", "done!", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
            else  if (employee_radio.isSelected()){
                int id=last_id+1;
                insert_id=(PreparedStatement) dbconn.prepareStatement("insert into person(id) value (?)");
                insert_id.setInt(1,id);
                int res =insert_id.executeUpdate();
                if (res==1){
                    st = (PreparedStatement) dbconn.prepareStatement("insert into employee(Employee_id,Employee_name,Employee_phone) values (?,?,?)  ");
                    st.setInt(1, id);
                    st.setString(2, name);
                    st.setString(3, phone);
                    int res2 = st.executeUpdate();
                    if (res2 == 1) {
                        st1 = (PreparedStatement) dbconn.prepareStatement("insert into account(username ,password,person_id,rule) values (?,?,?,?)");
                        st1.setString(1, username);
                        st1.setString(2, password);
                        st1.setInt(3, id);
                        st1.setString(4, "e");
                        int res1 = st1.executeUpdate();
                        if (res1==1)
                            JOptionPane.showMessageDialog(this, "Employee Added", "done!", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }

        }catch (Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error in adding","Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            try {
                dbconn.close();
                insert_id.close();
                resultSet.close();
                id_p.close();
                st.close();
                st1.close();

            }catch (SQLException e){
                e.printStackTrace();
            }
        }

    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton Sign_jButton;
    private javax.swing.ButtonGroup user_buttonGroup1;
    private javax.swing.JLabel cinema_icon;
    private javax.swing.JRadioButton coustomer_radio;
    private javax.swing.JRadioButton employee_radio;
    private javax.swing.JTextField fullname_field2;
    private javax.swing.JLabel hello_lable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton login_jButton;
    private javax.swing.JLabel login_labal;
    private javax.swing.JLabel password_labal1;
    private javax.swing.JTextField phon_field1;
    private javax.swing.JLabel phone_labal1;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_labal;
    private javax.swing.JLabel username_labal2;
    // End of variables declaration                   
}
