/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clas.*;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author hneen.
 */
public class Snack extends javax.swing.JFrame {

    /**
     * Creates new form Snak
     */
//to viwe data from the DB
    String [] listSnack;
    //for the item list  compenenit
    String [] listitem;
    //to view the items in the cart of the customer
    List<cartclass> cart1;
    int id_order=0;
//    int id_customer=0;
    int id_payment = 0;
    int num_items=0;
    double totalPrice_=0;

    int id_customer;
    movieName movie;
    public Snack() {
        initComponents();
    }

    public Snack(int idCustomer, movieName movie, double seatPrise) {
        initComponents();
        buttonGroup1.add(cashradio);
        buttonGroup1.add(CardRadio);
        holderName.setVisible(false);
        cardNum.setVisible(false);
        CCV.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        this.id_customer=idCustomer;
        this.movie=movie;
        this.totalPrice_=seatPrise+movie.getItem_prise();
        showCustomer_info(idCustomer);
        showCart();
        int i=0;
        if (getAllItems()!=null){
            listSnack =new String[50];
            for (Items b: getAllItems()){
                if (i!=50){
                    listSnack[i]=b.toString();
                    i++;
                }
            }
            snack.setModel(new DefaultComboBoxModel<>(listSnack));
            cart.setModel(new DefaultComboBoxModel<>());
        }
        try {
            DB n = new DB();
            Connection dbconn = n.connectDB();
            PreparedStatement id_p = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM cinema.order");
            ResultSet resultSet = id_p.executeQuery();
            while (resultSet.next()) {
                id_order = resultSet.getInt("order_id");
            }
            id_order++;
            PreparedStatement insert_id = (PreparedStatement) dbconn.prepareStatement("INSERT INTO cinema.order (order_id) VALUES (?)");
            insert_id.setInt(1,id_order );
            int res =insert_id.executeUpdate();
            if (res==1){

            }
            dbconn.close();
            id_p.close();
            resultSet.close();
            insert_id.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        try { DB n = new DB();
            Connection dbconn = n.connectDB();
            PreparedStatement id_pay = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM payment_methods");
            ResultSet resultSet = id_pay.executeQuery();
            while (resultSet.next()) {
                id_payment = resultSet.getInt("Payment_id");
            }
            id_payment++;
            PreparedStatement insert_id = (PreparedStatement) dbconn.prepareStatement("INSERT INTO payment_methods (Payment_id,Order_id) VALUES (?,?)");
            insert_id.setInt(1, id_payment);
            insert_id.setInt(2, id_order);
            int res = insert_id.executeUpdate();
            if (res == 1) {

            }
            dbconn.close();
            id_pay.close();
            resultSet.close();
            insert_id.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cart = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        snack = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        customer_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        deleteButtom = new javax.swing.JButton();
        cashradio = new javax.swing.JRadioButton();
        CardRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        holderName = new javax.swing.JTextField();
        CCV = new javax.swing.JTextField();
        cardNum = new javax.swing.JTextField();
        PrintTickat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        cart.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(cart);

        snack.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(snack);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Holle ");

        customer_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        customer_name.setForeground(new java.awt.Color(255, 204, 0));
        customer_name.setText("customear name");

        jLabel2.setIcon(new javax.swing.ImageIcon("cinema/icon/popcorn (1).png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Snack");

        AddButton.setBackground(new java.awt.Color(204, 204, 255));
        AddButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        AddButton.setForeground(new java.awt.Color(153, 0, 255));
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        deleteButtom.setBackground(new java.awt.Color(204, 204, 255));
        deleteButtom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        deleteButtom.setForeground(new java.awt.Color(153, 0, 255));
        deleteButtom.setText("Delete");
        deleteButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtomActionPerformed(evt);
            }
        });

        cashradio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cashradio.setForeground(new java.awt.Color(255, 204, 0));
        cashradio.setText("Cash");
        cashradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashradioActionPerformed(evt);
            }
        });

        CardRadio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        CardRadio.setForeground(new java.awt.Color(255, 204, 0));
        CardRadio.setText("Card");
        CardRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardRadioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 153));
        jLabel4.setText("Payment Method");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Holder Name");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Card Number");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("ccv");
        jLabel7.setToolTipText("");

        PrintTickat.setBackground(new java.awt.Color(255, 153, 153));
        PrintTickat.setForeground(new java.awt.Color(255, 51, 0));
        PrintTickat.setText("Print Ticket ");
        PrintTickat.setToolTipText("");
        PrintTickat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintTickatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                        .addComponent(holderName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cashradio)
                                                .addGap(32, 32, 32)
                                                .addComponent(CardRadio)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel7)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CCV, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customer_name)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrintTickat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(customer_name)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(deleteButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashradio)
                    .addComponent(CardRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintTickat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void deleteButtomActionPerformed(java.awt.event.ActionEvent evt) {
        int select=-1;
        select=cart.getSelectedIndex();
        if (select!=-1){
            try {
                deleteItem(select);
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, "reselect an items to be delete", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }


        }
        else {
            JOptionPane.showMessageDialog(this, "select an items to be delete", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cashradioActionPerformed(java.awt.event.ActionEvent evt) {
        showCArdfield(evt);
    }

    private void CardRadioActionPerformed(java.awt.event.ActionEvent evt) {
        showCArdfield(evt);
    }

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int select=-1;
        select=snack.getSelectedIndex();
        if (select!=-1){
            try {
                int index=-1;
                index=getAllItems().get(select).getItem_id();
                if (index!=-1 && id_order!=-1){
                    addToCArat(select,index,id_order);
                }

            }catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "reselect an items to be delete", "Error", JOptionPane.ERROR_MESSAGE);
//                e.printStackTrace();
            }


        }
        else {
            JOptionPane.showMessageDialog(this, "select an items to be delete", "Error", JOptionPane.ERROR_MESSAGE);
        }    }

    private void PrintTickatActionPerformed(java.awt.event.ActionEvent evt) {
            if (CardRadio.isSelected() || cashradio.isSelected()){
                card card = null;
                cash cash=null;
                if (CardRadio.isSelected()) {
                    setTotalPrice_();
                    int ID_pay = id_payment;
                    String holder = holderName.getText();
                    String card_num = cardNum.getText();
                    String CVV = CCV.getText();
                    if (holder.isEmpty() || card_num.isEmpty() || CVV.isEmpty() || totalPrice_ == 0) {
                        JOptionPane.showMessageDialog(this, "should not be empty", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (card_num.length()==16){
                            if (CVV.length()==3) {
                                if (card_num.matches("[0-9]+") && CVV.matches("[0-9]+")) {
                                    if (holder.matches("[a-zA-Z_]+")) {
                                        card = new card(ID_pay, totalPrice_, holder, card_num, CVV);
                                        sendPaynemt(card, num_items);
                                        long millis = System.currentTimeMillis();
                                        if (sendOrderRecord(id_order, id_customer, id_payment, new java.sql.Date(millis))) {
                                            if (card != null) {
                                                dispose();
                                                ticket d = new ticket(id_customer, num_items, card,id_order,movie);
                                                d.setTitle("dashbord");
                                                d.setVisible(true);
                                            }
                                        }


                                } else {
                                    JOptionPane.showMessageDialog(this, "Pleas Enter letters Only at holder name and type", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            }else {
                                    JOptionPane.showMessageDialog(this, "Pleas Enter number at card number and CVV", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            }else {
                                JOptionPane.showMessageDialog(this, "Pleas Enter 3 number at CVV filed", "Error", JOptionPane.ERROR_MESSAGE);
                            }

                        }else {
                            JOptionPane.showMessageDialog(this, "Pleas Enter 16 number at card number filed", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }else if (cashradio.isSelected()) {
                    setTotalPrice_();
                    String CURRENCY = "SAR";
                    cash = new cash(id_payment, totalPrice_, CURRENCY);
                    sendPaynemt(cash, num_items);
                        long millis=System.currentTimeMillis();
                        if (sendOrderRecord(id_order,id_customer,id_payment,new java.sql.Date(millis))){
                            if (cash!=null){
                                dispose();
                                ticket d = new ticket(id_customer, num_items, cash,id_order,movie);
                                d.setTitle("dashbord");
                                d.setVisible(true);
                            }
                        }
                    }
            }else {
                JOptionPane.showMessageDialog(this, "select the payment way first", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Snack().setVisible(true);
            }
        });
    }

    public List<Items> getAllItems(){
        List<Items> getingItems =null;
        ResultSet resultSet=null;
        PreparedStatement getMovie=null;
        DB n= new DB();
        Connection dbconn =n.connectDB();
        try {
            getMovie = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM snack");
            resultSet=getMovie.executeQuery();
            getingItems =new ArrayList<Items>();
            while (resultSet.next()){
                getingItems.add(new snack(resultSet.getInt("snack_id"),
                        resultSet.getString("snack_name"),
                        resultSet.getDouble("snack_price")));
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            try {
                dbconn.close();
                resultSet.close();
                getMovie.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return getingItems;
    }
    void showCustomer_info(int id_customer){
        DB conn=new DB();
        Connection dbconn=conn.connectDB();
        PreparedStatement st1=null;
        ResultSet cos_ifo =null;
        try {
                st1 = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM cinema.customer where coustomer_id = ? ");
                st1.setInt(1,id_customer);
                cos_ifo =st1.executeQuery();
                if (cos_ifo.next()){
                    customer_name.setText(cos_ifo.getString("coustomer_name"));
                    System.out.println("enterd to change name");
                }

            } catch (Exception e){
            e.printStackTrace();
        }finally {
            try {
                dbconn.close();
                st1.close();
                cos_ifo.close();
            }catch (Exception e){
                e.printStackTrace();
            }
        }

    }

    void showCart(){
        int i=0;
        listitem=new String[50];
        if (cart1!=null){
            for (cartclass s : cart1){
                if (i!=50){
                    listitem[i]= s.toString();
                    i++;
                }
            }
            cart.setModel(new DefaultComboBoxModel<>(listitem));
        }
    }

    void addToCArat(int select ,int id_item,int id) {

        DB n= new DB();
        Connection dbconn =n.connectDB();

        try {
            PreparedStatement exit = (PreparedStatement) dbconn.prepareStatement("select * from cart where order_id=? and item_id=?");
            exit.setInt(1, id);
            exit.setInt(2, id_item);
            ResultSet res = exit.executeQuery();
            if (res.next()){
                int numOfItem=res.getInt("num_item")+1;
                double priceOfitem =getAllItems().get(select).getItem_prise()* numOfItem;
                PreparedStatement update = (PreparedStatement) dbconn.prepareStatement("update cart set num_item =? , price =? where order_id=? and item_id=?");
                update.setInt(1,numOfItem);
                update.setDouble(2,priceOfitem);
                update.setInt(3, id);
                update.setInt(4, id_item);
                int update9 = update.executeUpdate();
                if (update9==1){
                    getAllCart();
                    showCart();
                    JOptionPane.showMessageDialog(this, "item stat up date to cart!", "done!", JOptionPane.INFORMATION_MESSAGE);
                }
                return;
            }

            if (res.next()==false){
                PreparedStatement  st = (PreparedStatement) dbconn.prepareStatement("insert into cart(order_id,item_id ,num_item,price) values (?,?,?,?)  ");
                st.setInt(1, id);
                st.setInt(2, id_item);
                st.setInt(3, 1);
                st.setDouble(4, getAllItems().get(select).getItem_prise());
                int res2 = st.executeUpdate();
                if (res2 == 1) {
                    getAllCart();
                    showCart();
                    JOptionPane.showMessageDialog(this, "item Added to cart!", "done!", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch (SQLException e) {

            e.printStackTrace();
        }finally {
            try {
                dbconn.close();
            }catch (SQLException e) {

                e.printStackTrace();
            }
        }
    }
    public List<cartclass> getAllCart(){
//        List<Integer> items_id=null;
        List<Items> getingItems =null;
        ResultSet resultSet=null;
        PreparedStatement getItems=null;
        PreparedStatement getSnack=null;
        DB n= new DB();
        Connection dbconn =n.connectDB();
        try {
            getItems = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM cart WHERE order_id=?");
            getItems.setInt(1,id_order);
            resultSet=getItems.executeQuery();
            cart1=new ArrayList<cartclass>();
            while (resultSet.next()){
                cart1.add(new cartclass(resultSet.getInt("order_id"),resultSet.getInt("item_id"),resultSet.getInt("num_item"),resultSet.getDouble("price")));
            }
            for (cartclass c:cart1){
                getSnack = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM snack where snack_id=?");
                getSnack.setInt(1,c.getItem_id());
                resultSet = getSnack.executeQuery();
                while (resultSet.next()) {
                    c.setItems(new snack(resultSet.getInt("snack_id"),
                            resultSet.getString("snack_name"),
                            resultSet.getDouble("snack_price")));
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            try {
                resultSet.close();
//                getSnack.close();
                getItems.close();
                dbconn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
//        return getingItems;
        return cart1;
    }

    void deleteItem(int select)  {
        DB n= new DB();
        Connection dbconn =n.connectDB();
        try {
            if (cart1.get(select).getNumItem()>1) {

                try {
                    PreparedStatement exit = (PreparedStatement) dbconn.prepareStatement("select * from cart where order_id=? and item_id=?");
                    exit.setInt(1, id_order);
                    exit.setInt(2, cart1.get(select).getItem_id());
                    ResultSet  res = exit.executeQuery();
                    if (res.next()) {
                        int numOfItem = res.getInt("num_item") - 1;
                        double priceOfitem =cart1.get(select).getItems().getItem_prise()* numOfItem;
                        PreparedStatement update = (PreparedStatement) dbconn.prepareStatement("update cart set num_item =? , price =? where order_id=? and item_id=?");
                        update.setInt(1, numOfItem);
                        update.setDouble(2, priceOfitem);
                        update.setInt(3, id_order);
                        update.setInt(4, cart1.get(select).getItem_id());
                        int update9 = update.executeUpdate();
                        if (update9 == 1) {
                            getAllCart();
                            showCart();
                        }

                        JOptionPane.showMessageDialog(this, "one item delete from cart!", "done!", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }

                } catch(SQLException e){
                    e.printStackTrace();
                }
            }
            if (cart1.get(select).getNumItem()==1){
                PreparedStatement delete = (PreparedStatement) dbconn.prepareStatement("DELETE FROM cart WHERE (order_id=? and item_id = ?)");
                delete.setInt(1, cart1.get(select).getOrder_id());
                delete.setInt(2, cart1.get(select).getItem_id());
                int reslt=delete.executeUpdate();
                if (reslt==1){
                    getAllCart();
                    showCart();
                    JOptionPane.showMessageDialog(this, "item delete from cart!", "done!", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }finally {
            try {
                dbconn.close();
            }catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    void showCArdfield(java.awt.event.ActionEvent evt){
        if (evt.getSource().equals(CardRadio)){
            holderName.setVisible(true);
            cardNum.setVisible(true);
            CCV.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
        }


        if (evt.getSource().equals(cashradio)){
            holderName.setVisible(false);
            cardNum.setVisible(false);
            CCV.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
        }

    }

    boolean sendOrderRecord(int id_order ,int custemer_id,int id_payment,java.sql.Date order_date){
        DB n= new DB();
        Connection dbconn =n.connectDB();
        PreparedStatement inserToOrderRecord=null;
        boolean send=false;
        try {
            inserToOrderRecord=dbconn.prepareStatement("insert into order_record(order_id,custemer_id,pay_id,order_date,movie_id) values (?,?,?,?,?)");
            inserToOrderRecord.setInt(1,id_order);
            inserToOrderRecord.setInt(2,custemer_id);
            inserToOrderRecord.setInt(3,id_payment);
            inserToOrderRecord.setDate(4,order_date);
            inserToOrderRecord.setInt(5,movie.getItem_id());
            int inser=inserToOrderRecord.executeUpdate();
            if (inser==1){
                PreparedStatement inserSeat=null;
                System.out.println("length of seates"+movie.getSeats().length);
                int inser3=-1;
                for (int i=0;i<movie.getSeats().length;i++){
                    send=false;
                     inserSeat=dbconn.prepareStatement("insert into seat(seat,movie_id,orderId,time) values (?,?,?,?)");
                     inserSeat.setString(1,movie.getSeats()[i]);
                     inserSeat.setInt(2,movie.getItem_id());
                     inserSeat.setInt(3,id_order);
                     inserSeat.setString(4,movie.getTimes());
                     inser3=inserSeat.executeUpdate();
                    if (inser3==1){
                        send=true;
                    }
                }


                return send;
            }

        }catch (SQLException e){
            e.printStackTrace();
        }finally {
            try {
                dbconn.close();
                inserToOrderRecord.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return false;
    }
    void sendPaynemt(Payment obj,int num_items){
        DB n= new DB();
        Connection dbconn =n.connectDB();

        try {
            if (obj instanceof card) {
                PreparedStatement card=dbconn.prepareStatement("insert into card(holder_name,ccv,card_number,Payment_id,Order_Total_price,num_items) values (?,?,?,?,?,?)");
                card.setString(1,((card) obj).getOwner_name());
                card.setString(2,((card) obj).getCCV());
                card.setString(3,((card) obj).getCard_num());
                card.setInt(4,obj.getPay_id());
                card.setDouble(5,obj.getTotal_price());
                card.setInt(6,num_items);
                int Reslt=card.executeUpdate();
                if (Reslt==1){
                    card.close();
                }
            }

            if (obj instanceof cash) {
                PreparedStatement cash=dbconn.prepareStatement("insert into cash(Payment_id,Order_Total_price,currency,num_items) values (?,?,?,?)");
                cash.setInt(1,obj.getPay_id());
                cash.setDouble(2,obj.getTotal_price());
                cash.setString(3,((cash) obj).getCurrency());
                cash.setInt(4,num_items);
                int reslt=cash.executeUpdate();
                if(reslt==1){
                    cash.close();
                }
            }
        }catch (SQLException e){
            e.printStackTrace();
        }finally {
            try {
                dbconn.close();
            }catch (SQLException e){
                e.printStackTrace();
            }
        }
    }

    void setTotalPrice_(){
        DB n= new DB();
        Connection dbconn =n.connectDB();
        try  {

            PreparedStatement totalPrice= (PreparedStatement) dbconn.prepareStatement("SELECT sum(price) , sum(num_item) from cart  where order_id=?");
            totalPrice.setInt(1, id_order);
            ResultSet res_price = totalPrice.executeQuery();
            if (res_price.next()) {
                num_items = res_price.getInt("sum(num_item)");
                this.totalPrice_ += res_price.getDouble("sum(price)");
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
    }




    // Variables declaration - do not modify                     
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField CCV;
    private javax.swing.JRadioButton CardRadio;
    private javax.swing.JButton PrintTickat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cardNum;
    private javax.swing.JList<String> cart;
    private javax.swing.JRadioButton cashradio;
    private javax.swing.JLabel customer_name;
    private javax.swing.JButton deleteButtom;
    private javax.swing.JTextField holderName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> snack;
    // End of variables declaration                   
}
