/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import clas.*;
import clas.Payment;
import clas.card;
import clas.cartclass;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author hneen.
 */
public class ticket extends javax.swing.JFrame {

    /**
     * Creates new form ticket
     */
movieName movie;
    Customer cous;
    List<cartclass> cart;
    public ticket() {
        initComponents();
    }

    public ticket(int idCustomer, int numItems, Payment pay,int idOrder,movieName movie) {
        initComponents();
        this.movie=movie;
        showCustomer_info(idCustomer);
        getAllCart(idOrder);
        jTextArea1.setEnabled(false);
        jTextArea1.append(printBill(cous,numItems,pay,idOrder));
        jTextArea1.append("******* cart info *********");
        showCart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/cnema/icon/tickets.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Heiti TC", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("ticket summary");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 51, 0));
        jButton1.setText("Eixt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        login d= new login();
        d.setTitle("Dash Bord");
        d.setVisible(true);    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }
    void showCart(){

        if (cart!=null){
            for (cartclass b: cart){
                jTextArea1.append(b.toString());
            }
        }
    }
    void showCustomer_info(int id_customer) {
        DB conn = new DB();
        Connection dbconn = conn.connectDB();
        try {
            PreparedStatement st1 = (PreparedStatement)
                    dbconn.prepareStatement("select * from customer where coustomer_id = ? ");
            st1.setInt(1, id_customer);
            ResultSet emp_ifo = st1.executeQuery();
            if (emp_ifo.next()) {
                cous=new Customer(id_customer,emp_ifo.getString("coustomer_name"),emp_ifo.getString("coustomer_Phone"));
            }
            dbconn.close();
            st1.close();
            emp_ifo.close();
        }catch(Exception e) {
            e.printStackTrace();
        }
    }

    public List<Items> getAllCart(int id_order){
        List<Integer> items_id=null;
        List<Items> getingItems =null;
        ResultSet resultSet=null;
        DB n= new DB();
        Connection dbconn =n.connectDB();
        try {
            PreparedStatement getItems = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM cart WHERE order_id=?");
            getItems.setInt(1,id_order);
            resultSet=getItems.executeQuery();
            cart=new ArrayList<cartclass>();
            while (resultSet.next()){
                cart.add(new cartclass(resultSet.getInt("order_id"),resultSet.getInt("item_id"),resultSet.getInt("num_item"),resultSet.getDouble("price")));
            }

            for (cartclass c:cart){
                PreparedStatement getSnack = (PreparedStatement) dbconn.prepareStatement("SELECT * FROM snack where snack_id=?");
                getSnack.setInt(1,c.getItem_id());
                resultSet = getSnack.executeQuery();
                while (resultSet.next()) {
                    c.setItems(new snack(resultSet.getInt("snack_id"),
                            resultSet.getString("snack_name"),
                            resultSet.getDouble("snack_price")));
                }
                getSnack.close();
                resultSet.close();
            }

            getItems.close();
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            try {
                resultSet.close();
                dbconn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return getingItems;
    }
    String bill;
    String printBill(Customer customer, int num_items, Payment pay,int idOrder){
        if (pay instanceof cash){
                bill = "********************************\n" +
                        "*         Ticket Summery        *\n" +
                        "********************************\n" +
                        "  Order ID:    " +  idOrder+ "\n" +
                        "  Customer Information:\n" +
                        "  ID: " + customer.getId() + "\n" +
                        "  Name: " + customer.getName() + "\n" +
                        "  Phone: " + customer.getPhone() + "\n" +
                        "  Movie Name: " + movie.getItem_name()+ "\n" +
                        "  Movie Time: " + movie.getTimes()+ "\n" +
                        "  Movie Seats: " + movie.getSeats()+"\n" +
                        "  Number Of Items: " + num_items + "  Total Price: " + pay.getTotal_price() + "\n" +
                        "  Payment Way : Cash \n" ;
        }
        if (pay instanceof card){
                bill = "********************************\n" +
                        "*         Ticket Summery        *\n" +
                        "********************************\n" +
                        "  Order ID:    " +  idOrder+ "\n" +
                        "  Customer Information:\n" +
                        "  ID: " + customer.getId() + "\n" +
                        "  Name: " + customer.getName() + "\n" +
                        "  Phone: " + customer.getPhone() + "\n" +
                        "  Movie Name: " + movie.getItem_name()+ "\n" +
                        "  Movie Time: " + movie.getTimes()+ "\n" +
                        "  Movie Seats: " + movie.getSeats()+"\n" +
                        "  Number Of Items: " + num_items + "  Total Price: " + pay.getTotal_price() + "\n" +
                        "  Payment Way : card \n" ;
        }
        return bill;
    }



    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
